accounts/urls.py
from django.urls import path
from . import views
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path("", UserLoginView.as_view(), name="login"),
    path("register/", UserRegistrationView.as_view(), name="user_register"),
    path("logout/", UserLogoutView.as_view(), name="logout"),

    path("forgot-password/", ForgotPasswordView.as_view(), name="forgot-password"),
    path("reset-password/validate/<uidb64>/<token>/", ResetPasswordView.as_view(), name="reset_password_validate"),


    # Profile
    path('profile/', ProfileView.as_view(), name='profile_view'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile_update'),


    path('students/', StudentListView.as_view(), name='student_list'),
    path('addstudent/', AddStudentsView.as_view(), name='add_student'),
    path('student/edit/<pk>/', UpdateStudentView.as_view(), name='update_student'),
    path('student/delete/<pk>/', DeleteStudentsView.as_view(), name='delete_student'),


    path('add_libraryhistory/',AddLibraryRecord.as_view(),name='add_library'),
    path('libraryhistory',LibraryHistoryView.as_view(),name='libraryhistory'),
    path('update_libraryhistory/<pk>/', UpdateLibraryHistory.as_view(), name='update_history'),
    path('delete_libraryhistory/<pk>/', DeleteLibraryHistoryView.as_view(), name='delete_history'),



    path('addfeehistory', AddNewFeeRecord.as_view(), name='add_feehistory'),
    path('feehistory', FeeHistoryView.as_view(), name='feehistory'),
    path('update_feehistory/<pk>/', UpdateFeeHistory.as_view(), name='update_fee'),
    path('delete_feehistory/<pk>/', DeleteFeeHistory.as_view(), name='delete_fee'),


    # Role-based dashboards
    # path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('admin_dashboard/', AdminDashboardView.as_view(), name='admin_dashboard'),
    path('profile/<id>/', UserProfileView.as_view(), name='user_profile'),
    path('adduser',AddUserView.as_view(),name='adduser'),
    path('users/edit/<pk>/', UpdateUserView.as_view(), name='updateuser'),
    path('users/delete/<pk>/', DeleteUserView.as_view(), name='deleteuser'),


    path('staff_dashboard/', StaffDashboardView.as_view(), name='staff_dashboard'),
    path('staff_addstudent/', StaffCreatStudentView.as_view(), name='staff_addstudent'),
    path('staff_student/Update/<pk>/', StaffStudentUpdateView.as_view(), name='staff_updatestudent'),
    path('Staff_student/delete/<pk>/', StaffStudentDeleteView.as_view(), name='staff_deletestudent'),


    path('librarian_dashboard/', LibrarianDashboardView.as_view(), name='librarian_dashboard'),


    path('books',BookView.as_view(),name='book_list'),
    path('addbook',AddBooks.as_view(),name='addbook'),
    path('editbook/<pk>/',UpdateBooksView.as_view(),name='editbook'),
    path('deletebook/<pk>/',DeleteBookView.as_view(),name='deletebook'),
]

school_managment/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace= 'accounts'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import random

# Create your models here.

class CustomUser(AbstractUser):

    ROLE_CHOICES = (
        ('admin', 'Admin'),
        ('staff', 'Office Staff'),
        ('librarian', 'Librarian'),
    )

    email = models.EmailField(max_length=254, verbose_name='email address')
    role = models.CharField(max_length=10, choices=ROLE_CHOICES)

    # Add related_name to avoid conflicts
    groups = models.ManyToManyField(
        'auth.Group',
        related_name='customuser_groups',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.'
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='customuser_permissions',
        blank=True,
        help_text='Specific permissions for this user.'
    )

    
    def __str__(self):
        return self.username
    

class Profile(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    phone = models.CharField(max_length=15, blank=True, null=True)
    profile_photo = models.ImageField(upload_to='user_photos/', blank=True, null=True)
    dob = models.DateField(null=True, blank=True)
    location = models.CharField(max_length=200, blank=True, null=True)




class Student(models.Model):
    class_section = [
        ('A', 'A'),
        ('B', 'B'),
        ('C', 'C'),
    ]

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    date_of_birth = models.DateField()
    gender_choices = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    ]
    gender = models.CharField(max_length=1, choices=gender_choices)

    # Contact Information
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=15, unique=True)
    address = models.TextField()

    # Enrollment Information
    admission_number = models.CharField(max_length=4, unique=True, editable=False)
    date_of_enrollment = models.DateField(auto_now_add=True)
    current_class = models.CharField(max_length=50)
    section = models.CharField(max_length=10, choices=class_section)

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def save(self, *args, **kwargs):
        if not self.admission_number:
            self.admission_number = str(random.randint(1000, 9999))  # Generate random 4-digit number
        super(Student, self).save(*args, **kwargs)


class Library(models.Model):

    Avilable_Chances = [
        ('yes', 'Yes'),
        ('no', 'No'),
    ]

    book_title = models.CharField(max_length=225)
    book_author = models.CharField(max_length=200)
    book_avilability = models.CharField(max_length=10, choices=Avilable_Chances)

    def __str__(self):
        return self.book_title
    

class LibraryHistory(models.Model):

    STATUS_CHOICES = [
        ('borrowed', 'Borrowed'),
        ('returned', 'Returned'),


    ]

    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    book_name = models.ForeignKey(Library, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, null=True)
    issue_date = models.DateField(auto_now_add=True)
    return_date = models.DateTimeField(null=True, blank=True)


    def __str__(self):
        return f"{self.book_name} borrowed by {self.student.first_name} {self.student.last_name}"



class FeesHistory(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    payment_date = models.DateField()
    total_fees = models.DecimalField(max_digits=10, decimal_places=2)
    fees_paid = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    outstanding_fees = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return f"Fees history for {self.student} on {self.payment_date}"
    

    def save(self, *args, **kwargs):
        self.outstanding_fees = self.total_fees - self.fees_paid
        super().save(*args, **kwargs)


    

accounts/views.py
from django.core.mail import EmailMessage
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from school_managment.mixin import RedirectAuthenticatedUserMixin
from django.views.generic import FormView, TemplateView, View, ListView, CreateView, UpdateView, DeleteView
from django.conf import settings
from .forms import UserRegistrationForm, LoginForm, ForgotPasswordForm, ResetPasswordForm,UpdateUserForm,ProfileUpdateForm, CreateUserForm,StudentForm
from .forms import UpdateLibraryHistoryForm, FeeHistoryUpdateForm, AddBookForm
from django.urls import reverse, reverse_lazy
from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.contrib import messages
from .models import CustomUser, LibraryHistory,Profile, Student,FeesHistory,Library
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from .token import custom_token_generator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.paginator import Paginator

# Create your views here.

class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'home.html'


class UserRegistrationView(RedirectAuthenticatedUserMixin,FormView):
    template_name = 'accounts/registration.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy("accounts:home")

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'form': self.form_class()})
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if not form.is_valid():
            return render(request, self.template_name, {'form': form})

        user = form.save(commit=False)
        user.password = make_password(form.cleaned_data['password'])
        user.save()
        
        # Perform Login Function
        user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
        if user is not None:
            login(request, user)
            messages.success(
                self.request,
                f"Account created successfully for {user.first_name} {user.last_name}! You are now logged in.",
            )
            return redirect(self.success_url)
        else:
            messages.error(self.request, "Failed to log in after registration. Please try logging in manually.")
            return redirect("accounts:login")
        

class UserLoginView(RedirectAuthenticatedUserMixin, View):
    template_name = 'accounts/login.html'
    form_class = LoginForm
    success_url = reverse_lazy("accounts:home")

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f'Welcome, {user.first_name} {user.last_name}! You have successfully logged in.')
                next_url = request.GET.get('next', self.success_url)
                return redirect(next_url)
            else:
                messages.error(request, 'Invalid username or password. Please try again.')
        return render(request, self.template_name, {'form': form})
    

class UserLogoutView(View):
    def get(self, request):
        logout(request)
        messages.success(request, 'You have been successfully logged out.')
        return redirect(reverse('accounts:login'))
    


# Forgot Password
class ForgotPasswordView(RedirectAuthenticatedUserMixin, View):
    template_name = 'accounts/forgot_password.html'
    success_template_name = 'accounts/emailsendpage.html'
    form_class = ForgotPasswordForm
    
    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})
    
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            try:
                user = CustomUser.objects.get(email=email)
            except CustomUser.DoesNotExist:
                user = None
            
            if user is not None:
                current_site = get_current_site(request)
                mail_subject = 'Reset Your Password'
                message = render_to_string('accounts/reset_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': custom_token_generator.make_token(user),
                })

                send_email = EmailMessage(mail_subject, message, from_email=settings.DEFAULT_FROM_EMAIL, to=[email])
                send_email.content_subtype = 'html'
                send_email.send()
                
                context = {
                    'email': email,
                }
                return render(request, self.success_template_name, context)
            else:
                messages.error(request, 'Account does not exist.')
                return redirect('accounts:forgot-password')
        else:
            return render(request, self.template_name, {'form': form})
        


# Reset Password   
class ResetPasswordView(RedirectAuthenticatedUserMixin, View):
    template_name = "accounts/reset_password.html"
    form_class = ResetPasswordForm
    
    def get_user(self, uidb64):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            return CustomUser.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
            return None
    
    def get(self, request, uidb64, token):
        user = self.get_user(uidb64)
        
        if user is not None and custom_token_generator.check_token(user, token):
            form = self.form_class()
            return render(request, self.template_name, {'form': form})
        else:
            messages.error(request, 'This link has expired or is invalid.')
            return redirect('user:login')
    
    def post(self, request, uidb64, token):
        user = self.get_user(uidb64)
        
        if user is not None and custom_token_generator.check_token(user, token):
            form = self.form_class(request.POST)
            if form.is_valid():
                password = form.cleaned_data['password']
                confirm_password = form.cleaned_data['confirm_password']

                if password == confirm_password:
                    user.set_password(password)
                    user.save()
                    messages.success(request, 'Password reset successful. Please login with your new password.')
                    return redirect('user:login')
                else:
                    messages.error(request, 'Passwords do not match. Please try again.')
            return render(request, self.template_name, {'form': form})
        else:
            messages.error(request, 'This link has expired or is invalid.')
            return redirect('accounts:login')


# Profile View
class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile_view.html'

    def get_context_data(self, **kwargs):
        profile = Profile.objects.get_or_create(user=self.request.user)
        profile = Profile.objects.get(user=self.request.user)
        context = super().get_context_data(**kwargs) 
        context['profile'] = profile  
        return context


# Profile Update
class ProfileUpdateView(LoginRequiredMixin, View):
    template_name = 'accounts/profile_update.html'

    def get(self, request, *args, **kwargs):
        user = request.user
        profile, created = Profile.objects.get_or_create(user=user)


        user_form = UpdateUserForm(instance=user)
        profile_form = ProfileUpdateForm(instance=profile)

        context = {
            'user_form': user_form,
            'profile_form': profile_form,
            'profile': profile
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        user = request.user
        profile, created = Profile.objects.get_or_create(user=user)

        user_form = UpdateUserForm(request.POST, instance=user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect(reverse_lazy('accounts:profile_view'))  

        context = {
            'user_form': user_form,
            'profile_form': profile_form,
            'profile': profile
        }
        return render(request, self.template_name, context)



    



# Role-Based Dashboard View
# class DashboardView(LoginRequiredMixin, TemplateView):
#     template_name = 'dashboard/admin_dashboard.html'


class RoleRequiredMixn(UserPassesTestMixin):
    allowed_roles = []

    def test_func(self):
        user = self.request.user
        return user.is_superuser or (hasattr(user, 'role') and user.role in self.allowed_roles)
    
    def handle_no_permission(self):
        return redirect('accounts:login')
    

class StudentListView(RoleRequiredMixn ,LoginRequiredMixin, ListView):
    model = Student

accounts/templates/accounts/library/add_book.html
{% extends 'layout/base.html' %}

{% block title %}Add Book {% endblock title %}

{% block content %}

<div class="container">
    <div class="table-wrapper">

        <div class="table-title">
            <div class="row">
            <div class="col-sm-6">
                <h2>Manage <b>Library </b></h2>
            </div>
            <div class="col-sm-6">
                <!-- Use data-bs-toggle for Bootstrap 5 -->
                <a href="{% url 'accounts:libraryhistory' %}" class="btn btn-success"><i class="fa-solid fa-plus" data-bs-toggle="tooltip" style="color: #f7f7f7;"></i> <span>Back</span></a>
            </div>
            </div>
        </div>
      
        <form method="post" class="mt-4">
            {% csrf_token %}
            {{ form.non_field_errors }}
            
            <div class="form-group">
                <label for="book_title">Book Title</label>
                {{ form.book_title }}
                {% if form.book_title.errors %}
                    <small class="text-danger">
                        {{ form.book_title.errors }}
                    </small>
                {% endif %}
            </div>

            <div class="form-group">
                <label for="book_author">Author</label>
                {{ form.book_author }}
                {% if form.book_author.errors %}
                    <small class="text-danger">
                        {{ form.book_author.errors }}
                    </small>
                {% endif %}
            </div>

            <div class="form-group"></div>
                <label for="book_avilability">Avlability</label>
                {{ form.book_avilability }}
                {% if form.book_avilability.errors %}
                    <small class="text-danger">
                        {{ form.book_avilability.errors }}
                    </small>
                {% endif %}
            </div>
            
            <button type="submit" class="btn btn-primary mt-4 w-100">Save</button>
            {{ form.errors }}
        </form>

    </div>
  </div>


{% endblock content %}

{% block scripts %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>



{% endblock scripts %}

accounts/templates/accounts/library/books_lists.html
{% extends 'layout/base.html' %}

{% block dashboard_title %}Books Lists{% endblock dashboard_title %}

{% block content %}

<div class="container">
    <div class="table-wrapper">
      <div class="table-title">
        <div class="row">
          <div class="col-sm-6">
            <h2>{{user.role}}<b>Dashboard</b></h2>
          </div>
          {% block buttons %}
          <div class="col-sm-6">
            <a href="{% url 'accounts:librarian_dashboard' %}" class="btn btn-success"><i class="fa-solid fa-minus" data-bs-toggle="tooltip" style="color: #f0f2f5;"></i><span>Back</span></a>
          </div>
          {% endblock buttons %}
        </div>
      </div>
      
      {% block table_content %}

      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Book Name</th>
            <th>Author</th>
            <th>Avilability</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
            {% for book in books %}
          <tr>
            <td>{{ book.book_title }}</td>
            <td>{{ book.book_author }}</td>
            <td>{{ book.book_avilability }}</td>
            <td>
              <!-- Update modal trigger attributes -->
              <a href="{% url 'accounts:editbook' pk=book.id %}" class="edit"><i class="fa-solid fa-pen-to-square fa-xs" data-bs-toggle="tooltip" style="color: #42c328;" title="Edit"></i></a>
              <a href="#deleteBookModal" class="delete" data-bs-toggle="modal" data-book-id="{{ book.id }}"><i class="fa-regular fa-trash-can fa-xs" data-bs-toggle="tooltip" style="color: #ec1818;" title="Delete"></i></a>
            </td>
          </tr>
          {% endfor %}
          <!-- Other rows here -->
        </tbody>
      </table>

      {% endblock table_content %}
    </div>
  </div>

<div id="deleteBookModal" class="modal fade" tabindex="-1" aria-labelledby="deleteBooksModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
  
        <form id="deleteBookForm" method="post">
          {% csrf_token %}
          <div class="modal-header">						
            <h4 class="modal-title">Delete Record</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-hidden="true"></button>
          </div>
          <div class="modal-body">					
            <p>Are you sure you want to delete these Record?</p>
            <p class="text-warning"><small>This action cannot be undone.</small></p>
          </div>
          <div class="modal-footer">
            <input type="button" class="btn btn-default" data-bs-dismiss="modal" value="Cancel">
            <input type="submit" class="btn btn-danger" value="Delete">
          </div>
        </form>
      </div>
    </div>
</div>


{% endblock content %}


{% block scripts %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

<script>
  document.addEventListener('DOMContentLoaded', function () {
      var deleteLibraryModal = document.getElementById('deleteBookModal');
      deleteLibraryModal.addEventListener('show.bs.modal', function (event) {
          var button = event.relatedTarget; // Button that triggered the modal
          var bookId = button.getAttribute('data-book-id'); // Correct data-* attribute
          
          
          // Update the form action to include the student ID
          var form = document.getElementById('deleteBookForm');
          if (form) {
              // Update the form action to include the student ID
              form.action = "{% url 'accounts:deletebook' 0 %}".replace("0", bookId);
          } else {
              console.error("Form not found!");
          }
      });
  });
</script>


{% endblock scripts %}

accounts/templates/accounts/library/library_details.html
{% extends 'layout/base.html' %}

{% block title %}Library Details{% endblock title %}

{% block content %}

<div class="container">
    <div class="table-wrapper">
      <div class="table-title">
        <div class="row">
          <div class="col-sm-6">
            <h2>Manage <b>Library </b></h2>
          </div>
          <div class="col-sm-6">
            <!-- Use data-bs-toggle for Bootstrap 5 -->
            <a href="{% url 'accounts:add_library' %}" class="btn btn-success"><span>Add New Record</span></a>
            
          </div>
        </div>
      </div>
      
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Student Name</th>
            <th>Book Name</th>
            <th>status</th>
            <th>Issue Date</th>
            <th>Return Date</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
            {% for l in library_data %}
          <tr>
            <td>{{ l.student }}</td>
            <td>{{ l.book_name }}</td>
            <td>{{ l.status }}</td>
            <td>{{ l.issue_date }}</td>
            <td>{{ l.return_date }}</td>
            <td>
              <!-- Update modal trigger attributes -->
              <a href="{% url 'accounts:update_history' pk=l.id %}" class="edit"><i class="fa-solid fa-pen-to-square fa-xs" data-bs-toggle="tooltip" style="color: #42c328;" title="Edit"></i></a>
              <a href="#deleteLibraryModal" class="delete" data-bs-toggle="modal" data-library-id="{{ l.id }}"><i class="fa-regular fa-trash-can fa-xs" data-bs-toggle="tooltip" style="color: #ec1818;" title="Delete"></i></a>
            </td>
          </tr>
          {% endfor %}
          <!-- Other rows here -->
        </tbody>
      </table>

    </div>
  </div>

<div id="deleteLibraryModal" class="modal fade" tabindex="-1" aria-labelledby="deleteLibrarysModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <form id="deleteLibraryForm" method="post">
        {% csrf_token %}
        <div class="modal-header">						
          <h4 class="modal-title">Delete Record</h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-hidden="true"></button>
        </div>
        <div class="modal-body">					
          <p>Are you sure you want to delete these Record?</p>
          <p class="text-warning"><small>This action cannot be undone.</small></p>
        </div>
        <div class="modal-footer">
          <input type="button" class="btn btn-default" data-bs-dismiss="modal" value="Cancel">
          <input type="submit" class="btn btn-danger" value="Delete">
        </div>
      </form>
    </div>
  </div>
</div>


<!-- <div class="next-page"> -->
  <!-- {% if jobs.has_previous %}
  <a href="?page={{products.previous_page_number}}"><span><<</span></a>
  {% endif %} -->
  <!-- {% for i in students.paginator.page_range %}
  <a href="?paginate_by={{i}}"><span>{{i}}</span></a>
  {% endfor %} -->

  <!-- {% if jobs.has_next %}
  <a href="?page={{products.next_page_number}}"><span>>></span></a>
  {% endif %} -->
<!-- </div>  -->
{% endblock content %}

{% block scripts %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

<script>
  document.addEventListener('DOMContentLoaded', function () {
      var deleteLibraryModal = document.getElementById('deleteLibraryModal');
      deleteLibraryModal.addEventListener('show.bs.modal', function (event) {
          var button = event.relatedTarget; // Button that triggered the modal
          var libraryId = button.getAttribute('data-library-id'); // Correct data-* attribute
          console.log(libraryId);
          
          
          // Update the form action to include the student ID
          var form = document.getElementById('deleteLibraryForm');
          if (form) {
              // Update the form action to include the student ID
              form.action = "{% url 'accounts:delete_history' 0 %}".replace("0", libraryId);
          } else {
              console.error("Form not found!");
          }
      });
  });
</script>


{% endblock scripts %}

accounts/templates/accounts/library/update_libraryhistory.html
{% extends 'layout/base.html' %}

{% block title %}update Library History{% endblock title %}

{% block content %}

<div class="container">
    <div class="table-wrapper">

        <div class="table-title">
            <div class="row">
            <div class="col-sm-6">
                <h2>Manage <b>Library </b></h2>
            </div>
            <div class="col-sm-6">
                <!-- Use data-bs-toggle for Bootstrap 5 -->
                <a href="{% url 'accounts:libraryhistory' %}" class="btn btn-success"><i class="fa-solid fa-plus" data-bs-toggle="tooltip" style="color: #f7f7f7;"></i> <span>Back</span></a>
            </div>
            </div>
        </div>
      
        <form method="post" class="mt-4">
            {% csrf_token %}
            {{ form.non_field_errors }}
            
            <div class="form-group">
                <label for="student">Student</label>
                {{ form.student }}
                {% if form.student.errors %}
                    <small class="text-danger">
                        {{ form.student.errors }}
                    </small>
                {% endif %}
            </div>

            <div class="form-group">
                <label for="book_name">Book Name</label>
                {{ form.book_name }}
                {% if form.book_name.errors %}
                    <small class="text-danger">
                        {{ form.book_name.errors }}
                    </small>
                {% endif %}
            </div>

            <div class="form-group"></div>
                <label for="status">Status</label>
                {{ form.status }}
                {% if form.status.errors %}
                    <small class="text-danger">
                        {{ form.status.errors }}
                    </small>
                {% endif %}
            </div>

            <div class="form-group">
                <label for="return_date">Return Date</label>
                {{ form.return_date }}
                {% if form.return_date.errors %}
                    <small class="text-danger">
                        {{ form.return_date.errors }}
                    </small>
                {% endif %}
            </div>
            
            <button type="submit" class="btn btn-primary mt-4 w-100">Save</button>
            {{ form.errors }}
        </form>

    </div>
  </div>


{% endblock content %}

{% block scripts %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>



{% endblock scripts %}