accounts/urls.py
from django.urls import path
from . import views
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path("", UserLoginView.as_view(), name="login"),
    path("register/", UserRegistrationView.as_view(), name="user_register"),
    path("logout/", UserLogoutView.as_view(), name="logout"),

    path("forgot-password/", ForgotPasswordView.as_view(), name="forgot-password"),
    path("reset-password/validate/<uidb64>/<token>/", ResetPasswordView.as_view(), name="reset_password_validate"),


    # Profile
    path('profile/', ProfileView.as_view(), name='profile_view'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile_update'),


    path('students/', StudentListView.as_view(), name='student_list'),
    path('addstudent/', AddStudentsView.as_view(), name='add_student'),
    path('student/edit/<pk>/', UpdateStudentView.as_view(), name='update_student'),
    path('student/delete/<pk>/', DeleteStudentsView.as_view(), name='delete_student'),


    path('add_libraryhistory/',AddLibraryRecord.as_view(),name='add_library'),
    path('libraryhistory',LibraryHistoryView.as_view(),name='libraryhistory'),
    path('update_libraryhistory/<pk>/', UpdateLibraryHistory.as_view(), name='update_history'),
    path('delete_libraryhistory/<pk>/', DeleteLibraryHistoryView.as_view(), name='delete_history'),



    path('addfeehistory', AddNewFeeRecord.as_view(), name='add_feehistory'),
    path('feehistory', FeeHistoryView.as_view(), name='feehistory'),
    path('update_feehistory/<pk>/', UpdateFeeHistory.as_view(), name='update_fee'),
    path('delete_feehistory/<pk>/', DeleteFeeHistory.as_view(), name='delete_fee'),


    # Role-based dashboards
    # path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('admin_dashboard/', AdminDashboardView.as_view(), name='admin_dashboard'),
    path('profile/<id>/', UserProfileView.as_view(), name='user_profile'),
    path('adduser',AddUserView.as_view(),name='adduser'),
    path('users/edit/<pk>/', UpdateUserView.as_view(), name='updateuser'),
    path('users/delete/<pk>/', DeleteUserView.as_view(), name='deleteuser'),


    path('staff_dashboard/', StaffDashboardView.as_view(), name='staff_dashboard'),
    path('staff_addstudent/', StaffCreatStudentView.as_view(), name='staff_addstudent'),
    path('staff_student/Update/<pk>/', StaffStudentUpdateView.as_view(), name='staff_updatestudent'),
    path('Staff_student/delete/<pk>/', StaffStudentDeleteView.as_view(), name='staff_deletestudent'),


    path('librarian_dashboard/', LibrarianDashboardView.as_view(), name='librarian_dashboard'),


    path('books',BookView.as_view(),name='book_list'),
    path('addbook',AddBooks.as_view(),name='addbook'),
    path('editbook/<pk>/',UpdateBooksView.as_view(),name='editbook'),
    path('deletebook/<pk>/',DeleteBookView.as_view(),name='deletebook'),
]

school_managment/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace= 'accounts'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/shared/navbar.html
{% load static %}
<style>
    .notification-icon .badge {
        left: 70%;
        transform: translateX(-50%);
        transform: translateY(-50%);
    }

    .navbar-toggler:focus {
        text-decoration: none;
        outline: 0;
        box-shadow: none; /* Remove box-shadow */
    }
</style>

<nav class="navbar navbar-light p-3" style="background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(97,97,164,1) 0%, rgba(88,160,175,1) 53%);
 color: white;">
    <div class="container-fluid">
        <a class="navbar-brand" href=""><h3>GVR Schools</h3></a>
        <button class="navbar-toggler collapse-nav" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="d-flex align-items-center main-nav">
            <div class="notification-icon-container me-3">
                
                {% if user.is_authenticated %}
                <a class="btn btn-outline-custom ms-2" href="{% url 'accounts:home' %}">Home</a>
                <button id="notificationButton" class="notification-icon btn btn-link position-relative" type="button" data-bs-toggle="modal" data-bs-target="#notificationModal">
                    <i class="fa-regular fa-bell"></i>
                    <span id="notificationCount" class="badge bg-danger rounded-pill position-absolute top-0 translate-middle p-1 ps-1 d-none" style="font-size: 0.7rem;">
                        <span class="visually-hidden">unread messages</span>
                    </span>
                </button>
                {% endif %}
            </div>

            <div class="btn-group">
                {% if user.is_authenticated %}
                
                <button class="profile-icon btn btn-link" type="button" id="profileDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fa-regular fa-user"></i>
                    <a class="btn btn-outline-custom" href="">{{user.first_name}} {{user.last_name}}</a>
                </button>
                <ul class="dropdown-menu dropdown-menu-end mt-3" aria-labelledby="profileDropdown">
                    <li><a class="dropdown-item" href="{% url 'accounts:profile_view' %}">Profile</a></li>
                    
                    {% if user.is_superuser or user.role == "admin" %}
                    <li class="nav-item">
                        <a class="dropdown-item" href="{% url 'accounts:admin_dashboard' %}">Admin Dashboard</a>
                    </li>
                    {% elif user.role == 'staff' %}
                    <li class="nav-item">
                        <a class="dropdown-item" href="{% url 'accounts:staff_dashboard' %}">Staff Dashboard</a>
                    </li>
                    {% elif user.role == 'librarian' %}
                    <li class="nav-item">
                        <a class="dropdown-item" href="{% url 'accounts:librarian_dashboard' %}">librarian Dashboard</a>
                    </li>

                    {% endif %}
                    
                    <li><a class="dropdown-item" href="">Messages</a></li>
                    {% comment %} <li><a class="dropdown-item" href="#">Logout</a></li> {% endcomment %}
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
                </ul>
                {% else %}
                <a class="btn btn-outline-custom ms-2" href="{% url 'accounts:login' %}">Log In</a>
                <a class="btn btn-outline-custom ms-2" href="{% url 'accounts:user_register' %}">Register</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

<div class="collapse collapse-nav" id="navbarNav">
    <div class="card mt-3 m-3">
        <div class="card-body">
            <div class="d-flex justify-content-end">
                <div class="notification-icon-container me-3">
                    {% if user.is_authenticated %}
                    <button id="notificationButton2" class="notification-icon btn btn-link position-relative" type="button" data-bs-toggle="modal" data-bs-target="#notificationModal">
                        <i class="fa-regular fa-bell"></i>
                        <span id="notificationCount2" class="badge bg-danger rounded-pill position-absolute top-0 translate-middle p-1 ps-1 d-none" style="font-size: 0.7rem;">
                            <span class="visually-hidden">unread messages</span>
                        </span>
                    </button>
                    {% endif %}
                </div>

                <div class="btn-group">
                    {% if user.is_authenticated %}
                    <button class="profile-icon btn btn-link" type="button" id="profileDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa-regular fa-user"></i>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end mt-3" aria-labelledby="profileDropdown">
                        <li><a class="dropdown-item" href="{% url 'accounts:profile_view' %}">Profile</a></li>
                        <li><a class="dropdown-item" href="">Messages</a></li>
                        {% comment %} <li><a class="dropdown-item" href="">Logout</a></li> {% endcomment %}
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
                    </ul>
                    {% else %}
                    <a class="btn btn-outline-custom ms-2" href="{% url 'accounts:login' %}">Log In</a>
                    <a class="btn btn-outline-custom ms-2" href="{% url 'accounts:user_register' %}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>